name = "HttpIO"
uuid = "1b65e21f-aef0-43ee-882b-ae2d1a27cbc4"
authors = ["Jialin Ma <jma@broadinstitute.org> and contributors"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
